#!/usr/bin/env bash
# Start Baidu Unlimited-OCR vLLM containers — one per GPU.
#
# Each container exposes 8000 inside and is mapped to a unique host port
# (8002, 8102, 8202, ...). The OCR stage reads UNLIMITED_OCR_BASE_URLS to
# round-robin requests across them.
#
# Usage:
#   ./scripts/start_unlimited_ocr.sh                # auto-detect GPUs
#   HVB_OCR_GPUS=0,1 ./scripts/start_unlimited_ocr.sh
#   HVB_OCR_GPUS=0 ./scripts/start_unlimited_ocr.sh # single GPU
#
# After startup, export the endpoints so the OCR stage picks them up:
#   export UNLIMITED_OCR_BASE_URLS="http://localhost:8002/v1,http://localhost:8102/v1"
# (this script prints the exact line to copy-paste).
set -euo pipefail

GPUS="${HVB_OCR_GPUS:-0,1}"
IFS=',' read -ra GPU_LIST <<< "$GPUS"

BASE_PORT=8002
IMAGE="vllm/vllm-openai:unlimited-ocr"
MODEL="baidu/Unlimited-OCR"
MEM_UTIL="${HVB_OCR_MEM_UTIL:-0.92}"
MAX_MODEL_LEN="${HVB_OCR_MAX_MODEL_LEN:-8192}"

URLS=()
for i in "${!GPU_LIST[@]}"; do
    gpu="${GPU_LIST[$i]}"
    port=$((BASE_PORT + i * 100))
    name="unlimited-ocr-gpu${gpu}"

    # Remove any stale container with the same name.
    if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
        echo "[start_unlimited_ocr] removing stale container $name"
        docker rm -f "$name" >/dev/null
    fi

    echo "[start_unlimited_ocr] GPU $gpu -> port $port ($name)"
    docker run -d --name "$name" \
        --gpus "device=$gpu" \
        -p "$port:8000" \
        -e HF_TOKEN="${HF_TOKEN:-}" \
        -v unlimited-ocr-gpu${gpu}:/root/.cache/huggingface \
        --restart unless-stopped \
        "$IMAGE" "$MODEL" \
        --trust-remote-code \
        --logits_processors vllm.model_executor.models.unlimited_ocr:NGramPerReqLogitsProcessor \
        --no-enable-prefix-caching --mm-processor-cache-gb 0 \
        --gpu-memory-utilization "$MEM_UTIL" \
        --max-model-len "$MAX_MODEL_LEN" \
        --port 8000 >/dev/null

    URLS+=("http://localhost:$port/v1")
done

# Join URLs as comma-separated string.
JOIN=$(IFS=','; echo "${URLS[*]}")

# Persist endpoints to a sourceable env file. run_pipeline.sh auto-loads it,
# so user does not need to re-export between shell sessions.
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.unlimited_ocr.env"
{
    echo "# Auto-generated by start_unlimited_ocr.sh — do not edit."
    echo "# Endpoints for Baidu Unlimited-OCR vLLM containers."
    echo "export UNLIMITED_OCR_BASE_URLS=\"$JOIN\""
    echo "export HVB_OCR_BACKEND=unlimited"
} > "$ENV_FILE"

# Wait for all endpoints to become healthy so caller can start OCR immediately.
echo
echo "[start_unlimited_ocr] ${#URLS[@]} container(s) launched. Waiting for /models …"
DEADLINE=$((SECONDS + 1200))  # 20 min cap (first run pulls ~7GB weights)
for u in "${URLS[@]}"; do
    until curl -fsS "$u/models" >/dev/null 2>&1; do
        if [ "$SECONDS" -gt "$DEADLINE" ]; then
            echo "[start_unlimited_ocr] TIMEOUT waiting on $u"
            echo "[start_unlimited_ocr] check container logs: docker logs unlimited-ocr-gpu<N>"
            exit 1
        fi
        sleep 5
    done
    echo "[start_unlimited_ocr]   ready: $u"
done

echo
echo "[start_unlimited_ocr] Endpoints written to $ENV_FILE"
echo "[start_unlimited_ocr] run_pipeline.sh auto-loads it, or source manually:"
echo "    source $ENV_FILE"
echo "[start_unlimited_ocr] Effective: UNLIMITED_OCR_BASE_URLS=$JOIN"
